# Generated by Django 5.1.5 on 2025-01-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
